__default__:
  account: "mutationalscanning"
  cpus-per-task: "{threads}"
  time: "04:00:00"
  mem: 16000
  gpus: 0
  partition: "normal"
  output: "logs/{rule}-%j.out"
  error: "logs/{rule}-%j.err"

prepare_sequences:
  account: "mutationalscanning"
  cpus-per-task: "{threads}"
  time: "04:00:00"
  mem: 32000
  partition: "gpu"
  gpus: 1
  output: "logs/{rule}-%j.out"
  error: "logs/{rule}-%j.err"


